### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by andrey1103** [darkalchemy/Pu-239-Installer#1]
./installer.sh: 150: ./installer.sh: [[: not found
./installer.sh: 155: ./installer.sh: [[: not found
-e You must set the DB Flavor to either Percona or MariaDB

The database is set to Percona tried to change to MariaDB , same error.

**Comment by darkalchemy** [comment]
I missed this until now. I will look into it.
Thanks

**Comment by darkalchemy** [comment]
I believe this has been fixed.

If you are still getting this, please feel free to re-open this issue.
