### ISSUE TITLE
Error at install 

### ISSUE THREAD

**Issue by Darkspac3** [darkalchemy/Pu-239-Installer#2]
Hello
 thanks for this script but i have error into excecute this command :  sudo ./installer.sh

`
gpg: keyring `/tmp/tmp9n2qpcp0/secring.gpg' created
gpg: keyring `/tmp/tmp9n2qpcp0/pubring.gpg' created
gpg: requesting key C300EE8C from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp9n2qpcp0/trustdb.gpg: trustdb created
gpg: key C300EE8C: public key "Launchpad Stable" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
gpg: keyring `/tmp/tmpm4jixa35/secring.gpg' created
gpg: keyring `/tmp/tmpm4jixa35/pubring.gpg' created
gpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpm4jixa35/trustdb.gpg: trustdb created
gpg: key E5267A6C: public key "Launchpad PPA for Ond\xc5\x99ej Sur▒" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
'ascii' codec can't decode byte 0xc5 in position 92: ordinal not in range(128)
dark@3848:~$
`

**Comment by darkalchemy** [comment]
I have just tested this in both 16.04 LTS and 18.04 LTS and I am not seeing this issue.

If you are still getting this, please feel free to re-open this issue.
